column_headers = [
    "feed_product_type", "item_sku", "brand_name", "update_delete", "item_name", 
    "color_name", "color_map", "size_name", "size_map", "generic_keywords", 
    "bullet_point1", "bullet_point2", "bullet_point3", "bullet_point4", "bullet_point5", 
    "product_description", "standard_price", "sale_price", "sale_from_date", "sale_end_date", 
    "product_site_launch_date", "merchant_release_date", "recommended_browse_nodes", 
    "external_product_id", "external_product_id_type", "main_image_url", "other_image_url1", 
    "other_image_url2", "other_image_url3", "other_image_url4", "other_image_url5", "other_image_url6", "other_image_url7", "other_image_url8",
    "swatch_image_url", "parent_child", "parent_sku", "relationship_type", "variation_theme", 
    "material_composition", "care_instructions", "closure_type", "neck_style", "weave_type", 
    "department_name", "sleeve_type", "merchant_shipping_group_name", "model", "part_number", 
    "model_name", "outer_material_type", "manufacturer", "language_value1", "language_value2", "quantity", 
    "inner_material_type", "target_gender", "age_range_description", "apparel_size_system", 
    "apparel_size_class", "apparel_size", "apparel_body_type", "apparel_height_type", 
    "shapewear_size_system", "shapewear_size_class", "shapewear_size", "shapewear_body_type", 
    "shapewear_height_type", "bottoms_size_system", "bottoms_size_class", "bottoms_size", 
    "bottoms_body_type", "bottoms_height_type", "skirt_size_system", "skirt_size_class", 
    "skirt_size", "skirt_body_type", "skirt_height_type", "shirt_size_system", "shirt_size_class", 
    "shirt_size", "shirt_body_type", "shirt_height_type", "style_name", "is_autographed", 
    "item_type_name", "occasion_type1", "occasion_type2", "occasion_type3", "occasion_type4", 
    "occasion_type5", "sport_type1", "sport_type2", "collection_name", "material_type1", 
    "material_type2", "material_type3", "target_audience_keywords1", "target_audience_keywords2", 
    "target_audience_keywords3", "target_audience_keywords4", "target_audience_keywords5", 
    "lifestyle1", "lifestyle2", "lifestyle3", "lifestyle4", "lifestyle5", "lifestyle6", 
    "lifestyle7", "lifestyle8", "lifestyle9", "lifestyle10", "fur_description", "fit_type1", 
    "fit_type2", "fit_type3", "fit_type4", "fit_type5", "collar_style", "pocket_description", 
    "theme", "lining_description", "league_name", "lifecycle_supply_type", "pattern_name", 
    "pattern_type", "special_features1", "special_features2", "special_features3", 
    "special_features4", "special_features5", "special_features6", "special_features7", "special_features8", "special_features9", "special_features10",
    "platinum_keywords1", "platinum_keywords2", "platinum_keywords3", "platinum_keywords4", 
    "platinum_keywords5", "seasons", "number_of_boxes", "water_resistance_level", "number_of_pieces", 
    "top_style", "rise_style", "front_style", "fabric_wash", "bottom_style", "strap_type", 
    "number_of_pockets", "waist_style", "item_length_description", "band_size_num", 
    "band_size_num_unit_of_measure", "country_of_origin", "supplier_declared_dg_hz_regulation1", 
    "item_weight", "item_weight_unit_of_measure", "fabric_type", "flash_point", 
    "supplier_declared_material_regulation1", "cpsia_cautionary_statement1", "condition_type", 
    "currency", "number_of_items", "map_price", "list_price_with_tax", "item_package_quantity", 
    "list_price", "other_image_url_ps06"
]

column_map = {
            "SKU": None,
            "颜色": None,
            "尺寸": None,
            "水洗唛材质": None,
            "亚马逊建议价": None,
            "代理链接 1": None,
            "代理链接 2": None,
            "代理链接 3": None,
            "代理链接 4": None,
            "代理链接 5": None,
            "代理链接 6": None,
            "代理链接 7": None,
            "代理链接 8": None,
            "代理链接 9": None
        }

# 创建颜色哈希表
fr_color_Map = {
    'brown': 'Marron',
    'purple pink': 'Violet rose',
    'purple': 'Violet',
    'vermilion': 'Vermillon',
    'fluorescent green': 'Vert fluorescent',
    'fluorescence yellow': 'Fluorescence jaune',
    'fuchsia': 'Fuchsia',
    'silver': 'Argenté',
    'champagne': 'Champagne',
    'watermelon red': 'Rouge Pastèque',
    'camouflage': 'Camouflage',
    'sky blue': 'Bleu ciel',
    'dark purple': 'Violet foncé',
    'dark green': 'Vert foncé',
    'dark blue': 'Bleu foncé',
    'deep blue': 'Bleu profond',
    'dark gray': 'Gris foncé',
    'dark grey': 'Gris foncé',
    'deep red': 'Rouge foncé',
    'dark red': 'Rouge foncé',
    'snake pattern': 'Motif de serpent',
    'colorful': 'Coloré',
    'clear': 'Transparent',
    'bronze': 'Bronze',
    'cyan': 'cyan',
    'light brown': 'Brun clair',
    'light purple': 'Violet clair',
    'light blue': 'Bleu clair',
    'light gray': 'Gris clair',
    'earthy yellow': 'Jaune terreux',
    'cow pattern': 'Motif vache',
    'cow print': 'Impression de vache',
    'beige': 'Beige',
    'rose gold': 'Or rose',
    'turquoise': 'Turquoise',
    'green': 'Vert',
    'camel': 'chameau',
    'light green': 'Vert clair',
    'light pink': 'Rose clair',
    'light bule': 'Bleu clair',
    'blue': 'Bleu',
    'khaki': 'Kaki',
    'coffee': 'Café',
    'army green': 'Armée verte',
    'wine red': 'Vin rouge',
    'wine': 'Vin rouge',
    'golden': 'Dorée',
    'ginger': 'Gingembre',
    'gray': 'Gris',
    'grey': 'Gris',
    'yellow': 'Jaune',
    'gold': 'Or',
    'royal blue': 'Bleu royal',
    'red': 'rouge',
    'black': 'Noir',
    'navy blue': 'Marine',
    'navy': 'Marine',
    'complexion': 'Complexion',
    'pink': 'Rose',
    'hot pink': 'Rose vif',
    'multicolor': 'Multicolore',
    'multicolour': 'Multicolore',
    'orange': 'Orange',
    'saffron': 'Safran',
    'ecru': 'Ecru',
    'leopard print': 'Imprimé léopard',
    'leopard': 'Léopard',
    'mint green': 'Menthe verte',
    'zebra': 'Zèbre',
    'white': 'Blanc',
    'multcolor': 'Multicolore'
}

fr_color_map_Map = {
    'brown': 'Marron',
    'purple pink': 'Violet',
    'purple': 'Violet',
    'vermilion': 'Rouge',
    'fluorescent green': 'Turquoise',
    'fluorescence yellow': 'Jaune',
    'fuchsia': 'Rouge',
    'silver': 'Argent',
    'champagne': 'Jaune',
    'watermelon red': 'Rouge',
    'camouflage': 'Multicolore',
    'sky blue': 'Turquoise',
    'dark purple': 'Violet',
    'dark green': 'Vert',
    'dark blue': 'Bleu',
    'deep blue': 'Bleu',
    'dark gray': 'Gris',
    'dark grey': 'Gris',
    'deep red': 'Rouge',
    'dark red': 'Rouge',
    'snake pattern': 'Multicolore',
    'colorful': 'Multicolore',
    'clear': 'Transparent',
    'bronze': 'Marron',
    'cyan': 'Vert',
    'light brown': 'Marron',
    'light purple': 'Violet',
    'light blue': 'Turquoise',
    'light gray': 'Ivoire',
    'earthy yellow': 'Beige',
    'cow pattern': 'Multicolore',
    'cow print': 'Multicolore',
    'beige': 'Beige',
    'rose gold': 'Rose',
    'turquoise': 'Turquoise',
    'green': 'Vert',
    'camel': 'Marron',
    'light green': 'Turquoise',
    'light pink': 'Rose',
    'light bule': 'Turquoise',
    'blue': 'Bleu',
    'khaki': 'Beige',
    'coffee': 'Marron',
    'army green': 'Multicolore',
    'wine red': 'Rouge',
    'wine': 'Rouge',
    'golden': 'Or',
    'ginger': 'Beige',
    'gray': 'Gris',
    'grey': 'Gris',
    'yellow': 'Jaune',
    'gold': 'Or',
    'royal blue': 'Turquoise',
    'red': 'Rouge',
    'black': 'Noir',
    'navy blue': 'Bleu',
    'navy': 'Bleu',
    'complexion': 'Ivoire',
    'pink': 'Rose',
    'hot pink': 'Rose',
    'multicolor': 'Multicolore',
    'multicolour': 'Multicolore',
    'orange': 'Orange',
    'saffron': 'Rouge',
    'ecru': 'Beige',
    'leopard print': 'Multicolore',
    'leopard': 'Multicolore',
    'mint green': 'Vert',
    'zebra': 'Multicolore',
    'white': 'Blanc',
    'multcolor': 'Multicolore'
}


us_Size_Mapping = {
    "XXS": "XXS",
    "2XS": "XXS",
    "XS": "XS",
    "S": "S",
    "M": "M",
    "L": "L",
    "XL": "XL",
    "XXL": "XXL",
    "2XL": "XXL",
    "L2": "XXL",
    "XXXL": "3XL",
    "3XL": "3XL",
    "L3": "3XL",
    "XXXXL": "4XL",
    "4XL": "4XL",
    "L4": "4XL",
    "XXXXXL": "5XL",
    "5XL": "5XL",
    "L5": "5XL",
    "XXXXXXL": "6XL",
    "6XL": "6XL",
    "L6": "6XL",
    "XXXXXXXL": "7XL",
    "7XL": "7XL",
    "L7": "7XL", 
    "110": "3 Jahre", 
    "120": "5 Jahre", 
    "130": "7 Jahre", 
    "140": "9 Jahre", 
    "150": "11 Jahre", 
    "160": "13 Jahre", 
    "One Size": "Einheitsgröße", 
}

us_size_map_Mapping = {
    'XXS': '2XS',
    '2XS': '2XS',
    'XS': 'XS',
    'S': 'S',
    'M': 'M',
    'L': 'L',
    'XL': 'XL',
    'XXL': '2XL',
    '2XL': '2XL',
    'L2': '2XL',
    'XXXL': '3XL',
    '3XL': '3XL',
    'L3': '3XL',
    'XXXXL': '4XL',
    '4XL': '4XL',
    'L4': '4XL',
    'XXXXXL': '5XL',
    '5XL': '5XL',
    'L5': '5XL',
    'XXXXXXL': '6XL',
    '6XL': '6XL',
    'L6': '6XL',
    'XXXXXXXL': '7XL',
    '7XL': '7XL',
    'L7': '7XL', 
    "110": "3-4 Jahre(110)", 
    "120": "4-5 Jahre(120)", 
    "130": "6-7 Jahre(130)", 
    "140": "8-9 Jahre(140)", 
    "150": "10-11 Jahre(150)", 
    "160": "12-13 Jahre(160)", 
    "One Size": "Einheitsgröße", 
}

Product_Type_Map_New = {
    "衬衫": "shirt",
    "长款上衣": "tunic",
    "运动衫": "sweatshirt",
    "背心": "vest",
    "连衣裙": "dress",
    "半身裙": "skirt",
    "外套": "coat",
    "罩衫": "kimono",
    "夹克": "blazer",
    "裤子": "pants",
    "短裤": "shorts",
    "毛衣": "sweater",
    "领带": "necktie",
    "内裤": "underpants",
    "泳装": "swimwear",
    "袜子": "socks",
    "内衣": "underwear",
    "睡衣": "pajamas",
    "睡袍": "nightgownnightshirt",
    "睡衣": "sleepwear",
    "套装": "suit",
    "长袍": "robe",
    "胸罩": "bra",
    "帽子": "hat",
    "围巾": "scarf",
    "背包": "backpack",
    "手提袋": "totebag",
    "腰带": "apparelbelt",
    "手套": "apparelgloves",
    "配饰": "accessory",
    "民族服装": "ethnicwear"
}

Product_Type_Map = {
    "衬衫": "shirt",
    "长款上衣": "shirt",
    "紧身短袖小衫": "shirt",
    "运动衫": "sweatshirt",
    "背心": "shirt",
    "毛衣": "sweater",
    "外衣": "outerwear",
    "外套": "coat",
    "西装外套": "blazer",
    "短裤": "pants",
    "裤子": "pants",
    "连衣裙": "dress",
    "半身裙": "skirt",
    "紧身胸衣": "shirt",
    "胸罩": "shirt",
    "内衣": "shirt",
    "内裤": "pants",
    "内衣裤": "undergarmentslip",
    "背带": "suspender",
    "手臂套": "armsleeve",
    "游泳衣": "swimwear",
    "运动服": "sweatshirt",
    "工作服": "pants",
    "长袍": "robe",
    "睡袍": "nightgownnightshirt",
    "睡衣两件套": "pajamas",
    "睡衣": "sleepwear",
    "束腰服": "waistcincher",
    "套装": "suit",
    "紧身裤": "tights",
    "紧身连衣裤": "leotard",
    "围裙": "apron",
    "袜子": "socks",
    "针织袜": "sockshosiery",
    "围巾": "scarf",
    "纱丽": "saree",
    "帽子": "hat",
    "背包": "backpack",
    "手提袋": "totebag",
    "护目镜": "safetyglasses",
    "领带": "necktie",
    "腰带": "apparelbelt",
    "行李箱": "luggage",
    "钥匙扣": "keychain",
    "鞋带": "shoelace",
    "耳罩": "earmuff",
    "手套": "apparelgloves",
    "手套": "apparelgloves",
    "防护手套": "protectiveglove",
    "食物围兜": "foodbib",
    "配饰": "accessory"
}

department_name_Map = {
    "女士": "Femme",
    "男士": "Homme",
    "男女通用": "Mixte",
    "女孩": "Fille",
    "男孩": "Garçon",
    "男女孩通用": "Mixte enfant",
    "女婴": "Bébé fille",
    "男婴": "Bébé garçon",
    "男女婴通用": "Mixte bébé"
}

site_Map={
    "美国":"US", "德国":"DE", "法国":"FR", "英国":"UK", "加拿大":"CA"
}

age_group_map = {
    "成人": "Adulte",
    "大孩子": "TEEN",
    "孩子": "Enfant",
    "小孩": "Tout-petit",
    "学步的儿童": "Poupon",
    "婴儿": "Nourrisson",
    "新生": "Nouveau-né"
}

gender_map = {
    "女士": "Féminin",
    "男士": "Masculin",
    "男女通用": "Unisexe",
}

neck_style_map = {
    "圆领": "Col rond",
    "V领": "Col en V",
    "船领": "Col bateau",
    "连帽": "À capuche",
    "露肩": "Épaules dénudées",
    "单肩领": "Une épaule",
    "高领": "Col roulé",
    "无肩带/抹胸": "Bandeau",
    "挂脖露背（Halter）": "halter_neck",
    "T形背": "Racer Back",
    "U型领": "Col en U",
    "斜领": "Col slash",
    "不对称领口": "asymmetric",
    "含孔领": "Cou trou de serrure",
    "Polo领": "Col polo",
    "Henley领": "Col henley",
    "纽扣": "Col à boutons",
    "网孔领": "Col en maille",
    "半拉链": "Col à fermeture éclair",
    "方领": "Col carré",
    "半高圆领": "Col mock",
    "心形颈": "Décolleté en cœur",
    "开叉领": "Col fendu",
    "披肩领": "Col châle",
    "无领领口": "Sans col"
}

pattern_map = {
    "纯色": "Uni",
    "简朴": "Plaine",
    "条纹": "À rayures",
    "有图案": "Impression",
    "文字": "Imprimée Lettre",
    "带花图案": "À fleurs",
    "动物图案": "Imprimé Animal",
    "格子": "À carreaux",
    "扎染": "Colorant de cravate",
    "豹纹": "Léopard",
    "迷彩": "Camouflage",
    "佩斯利纹": "Cachemire",
    "波尔卡圆点": "Pois",
    "几何": "Géométrique",
    "星星图案": "Étoile",
    "水波纹": "Moiré",
    "鱼骨纹": "Fischgrätmuster",
    "锯齿纹": "Chevron",
    "植物图案": "Botanique",
    "菱形格": "Argyle",
    "水果": "Fruit",
    "拼色": "Blocs De Couleurs",
    "银河": "Galaxie",
    "圣诞节": "Noël",
    "卡通": "Cartoon",
    "犬牙花纹": "Herringbone",
    "水果和蔬菜": "Fruits et Légumes",
    "爱心": "Cœur",
    "钻石": "Diamant",
    "蛇皮图案": "Imprimé peau de serpent",
}

clothing_style_map = {
    "经典": "Classic",
    "复古": "Retro",
    "现代": "Modern",
    "传统": "Traditional",
    "波西米亚风": "Bohemian",
    "休闲": "Casual",
    "优质": "Vintage",
}

skirt_length_map = {
    "超长": "Floor Length",
    "长裙": "Maxi",
    "到脚踝": "Ankle Length",
    "到小腿": "Calf Length",
    "中长裙": "Midi",
    "膝盖以下": "Below the Knee",
    "到膝盖": "Knee Length",
    "膝盖以上": "Above the Knee",
    "到大腿中部": "Mid Thigh Length",
    "短裙": "Mini"
}

fit_map = {
    "宽松": "Loose",
    "合身": "Fitted",
    "苗条": "Slim",
    "紧身": "Skinny Fit"
}

closure_map = {
    "系腰带": "Ceinture",
    "扣上": "buckle",
    "拉链": "Fermeture éclair",
    "绑上": "Cravate",
    "按钮": "Bouton",
    "拉绳": "Cordon de serrage",
    "穿上": "Pull on",
    "无关闭": "Pas de fermeture",
    "钩": "Hook and loop"
}

pocket_map = {
    "立体口袋": "Cargo",
    "工具口袋": "Carpenter",
    "无后袋": "No Back Pocket",
    "斜口袋": "Slant Pocket",
    "狭缝口袋": "Slit Pocket",
    "多用途口袋": "Utility Pocket",
    "直插口袋": "Straight Pocket",
    "开缝口袋": "Welt Pocket",
    "翻盖口袋": "Flap Pocket",
    "零钱袋": "Coin Pocket",
    "票袋": "Ticket Pocket",
    "斜线口袋": "Slash Pocket"
}

sleeve_map = {
    "长袖": "Long Sleeve",
    "短袖": "Short Sleeve",
    "无袖": "Sleeveless",
    "3/4 袖": "3/4 Sleeve",
    "半袖": "Half Sleeve",
    "背心": "Tanks",
    "露肩袖": "Cold Shoulder Sleeve",
    "和服袖": "Kimono Sleeve",
    "荷叶袖": "Ruffle Sleeve",
    "泡泡袖": "Puff Sleeve",
    "喇叭袖": "Bell Sleeve",
    "蝙蝠袖": "Batwing Sleeve",
    "蝴蝶袖": "Butterfly Sleeve",
    "气球袖": "Balloon Sleeve",
    "斗篷袖": "Cape Sleeve"
}

top_style_map = {
    "按钮": "Button Down",
    "吊带": "Cami",
    "挂脖": "Halter",
    "单肩": "One Shoulder",
    "T形背": "Racerback",
    "无肩带/管": "Strapless/Tube",
    "文胸": "Bralette",
    "露肩": "Off The Shoulder",
    "高领": "High Neck",
    "喇叭形": "Flared",
    "交叉背": "Crossback",
    "防晒衣": "Rashguard",
    "背心比基尼": "Tankini",
    "无上装比基尼": "Monokini",
    "延绳钓": "Longline",
    "抹胸": "Bandeau",
    "Push Up": "Push Up"
}

seasons_map = {
    "春天": "Spring",
    "夏天": "Summer",
    "秋天": "Autumn",
    "冬天": "Winter",
    "四季": "All"
}

#----------------------------------------

leg_style_map = {
    "脚踝": "Ankle",
    "靴型剪裁": "Boot Cut",
    "裁剪": "Cropped",
    "喇叭裤": "Flared",
    "紧身": "Skinny",
    "直筒": "Straight",
    "锥形": "Tapered",
    "裤装": "Trouser",
    "宽松": "Wide"
}

waist_style_map ={
"中腰": "Medium Waist",
"高腰": "High Waist",
"低腰": "Low Waist"
}

# item_type_map={
#     "衬衫": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"], 

#     "长款上衣": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"], 
    
#     "紧身短袖小衫": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"],
    
#     "运动衫": ["Sweater", "Hooded Sweatshirt", "Sweatshirt", "Cardigan Sweater", 
#     "Pullover Sweater", "Polo Sweater", "Sweater Vest", "Sweater", 
#     "Hooded Sweatshirt", "Sweatshirt", "Cardigan Sweater", "Pullover Sweater", 
#     "Polo Sweater", "Sweater Vest", "Sweater"],

#     "西装外套":["Business Casual Blazer", "Casual Blazer", "Sport Jacket", "Blazer"],

#     "胸罩": ["T-Shirt Bra", "Training Bra", "Full Coverage Bra", "Plunge Bra", 
#              "Sports Bra", "Bra", "Padded Bra", "Demi Bra", "Minimizer Bra", 
#              "Balconette Bra", "Push Up Bra"],

#     "游泳衣": ["One Piece Swimsuit", "Swim Trunks", "Tankini Set", "Swimwear Cover Up", 
#                   "Swimsuit Separates", "Swim Briefs", "Bikini Top", "Swim Shirt Set", 
#                   "Swimwear Cover Up Set", "Tankini Top", "Tankini Swimsuit", "Bikini Bottoms", 
#                   "Bikini", "Bikini Set", "Two Piece Swimsuit"],

#     "睡衣两件套/睡袍": ["Pajama Top", "Nightgown", "Bathrobe", "Pajama Bottom", "Night Shirt", 
#                    "Pajama Set"],

#     "套装": ["Business Suit Jacket", "Tuxedo Pants", "Tuxedo", "Tuxedo Jacket", 
#               "Suit - Skirt Set", "Suit - Dress Set", "Business Suit Vest", 
#               "Business Suit Pants Set"],

#     "帽子": ["Rain Hat", "Cowboy Hat", "Baseball Cap", "Sun Hat", "Cap", 
#              "Cold Weather Hat", "Hat", "Beanie Hat", "Cold Weather Headband"],
    
# }