column_headers = [
    "feed_product_type", "item_sku", "brand_name", "update_delete", "item_name", 
    "color_name", "color_map", "size_name", "size_map", "bullet_point1", 
    "bullet_point2", "bullet_point3", "bullet_point4", "bullet_point5", 
    "generic_keywords", "product_description", "standard_price", "sale_price", 
    "sale_from_date", "sale_end_date", "product_site_launch_date", 
    "merchant_release_date", "external_product_id", "external_product_id_type", 
    "item_type", "main_image_url", "other_image_url1", "other_image_url2", 
    "other_image_url3", "other_image_url4", "other_image_url5", "other_image_url6", "other_image_url7", "other_image_url8",
    "swatch_image_url", 
    "parent_child", "parent_sku", "relationship_type", "variation_theme", 
    "fabric_type", "care_instructions", 
    "closure_type", "neck_style", "department_name", "sleeve_type", 
    "merchant_shipping_group_name", "model", "model_name", "part_number", 
    "manufacturer", "quantity", "outer_material_type", 
    "inner_material_type", "target_gender", "age_range_description", 
    "apparel_size_system", "apparel_size_class", "apparel_size", 
    "apparel_body_type", "apparel_height_type", "shapewear_size_system", 
    "shapewear_size_class", "shapewear_size", "shapewear_body_type", 
    "shapewear_height_type", "bottoms_size_system", "bottoms_size_class", 
    "bottoms_size", "bottoms_body_type", "bottoms_height_type", 
    "skirt_size_system", "skirt_size_class", "skirt_size", "skirt_body_type", 
    "skirt_height_type", "shirt_size_system", "shirt_size_class", 
    "shirt_size", "shirt_body_type", "shirt_height_type", 
    "target_audience_keywords1", "target_audience_keywords2", 
    "target_audience_keywords3", "target_audience_keywords4", 
    "target_audience_keywords5", "style_name", "is_autographed", 
    "item_type_name", "occasion_type1", "occasion_type2", "occasion_type3", 
    "occasion_type4", "occasion_type5", "sport_type1", "sport_type2", 
    "collection_name", "material_type1", "material_type2", "material_type3", 
    "lifestyle1", "lifestyle2", "lifestyle3", "lifestyle4", "lifestyle5", 
    "lifestyle6", "lifestyle7", "lifestyle8", "lifestyle9", "lifestyle10", 
    "fit_type1", "fit_type2", "fit_type3", "fit_type4", "fit_type5", 
    "collar_style", "weave_type", "pocket_description", "theme", 
    "lining_description", "lifecycle_supply_type", "pattern_name", 
    "belt_style", "pattern_type", 
    "special_features1", "special_features2", "special_features3", 
    "special_features4", "special_features5", "top_style", 
    "water_resistance_level", "number_of_boxes", "number_of_pieces", 
    "seasons", "rise_style", "language_value1", 
    "platinum_keywords1", "platinum_keywords2", "platinum_keywords3", 
    "platinum_keywords4", "platinum_keywords5",
    "front_style", "fabric_wash", "strap_type", 
    "bottom_style", "leg_style", "number_of_pockets", "material_composition", 
    "waist_style", "item_length_description", "band_size_num", 
    "band_size_num_unit_of_measure", "cpsia_cautionary_statement1", 
    "item_weight_unit_of_measure", "item_weight", "country_of_origin", 
    "supplier_declared_dg_hz_regulation1", "supplier_declared_material_regulation1", 
    "list_price", "currency", "condition_type", "number_of_items", 
    "item_package_quantity", "recommended_browse_nodes", "league_name", "map_price", "list_price_with_tax"
]

column_map = {
            "SKU": None,
            "颜色": None,
            "尺寸": None,
            "水洗唛材质": None,
            "亚马逊建议价": None,
            "代理链接 1": None,
            "代理链接 2": None,
            "代理链接 3": None,
            "代理链接 4": None,
            "代理链接 5": None,
            "代理链接 6": None,
            "代理链接 7": None,
            "代理链接 8": None,
            "代理链接 9": None
        }

# 创建颜色哈希表
us_color_Map = {
     "yellow": "Yellows",
    "gray": "Grey",
    "pink": "Pink",
    "white": "White",
    "black": "Black",
    "coffee": "Brown",
    "khaki": "Beige",
    "wine red": "Red",
    "navy": "Blues",
    "orange": "Orange",
    "red": "Reds",
    "green": "Greens",
    "blue": "Blues",
    "multicolor": "Multi",
    "brown": "Browns",
    "army green": "Greens",
    "dark gray": "Greys",
    "dark blue": "Blues",
    "mint green": "Greens",
    "hot pink": "Reds",
    "wine": "Reds",
    "beige": "Beige",
    "purple": "Purples",
    "sky blue": "Blues",
    "colorful": "Multi",
    "silver": "Silvers",
    "ecru": "Beige",
    "gold": "Golds",
    "turquoise": "Greens",
    "light blue": "Blues",
    "rose gold": "Golds",
    "light green": "Greens",
    "dark green": "Greens",
    "watermelon red": "Reds",
    "camouflage": "Greens",
    "light brown": "Brown",
    "light gray": "Grey",
    "complexion": "Beige",
    "grey": "Grey",
    "royal blue": "Blues",
    "light purple": "Purples",
    "cyan": "Greens",
    "bronze": "Brown",
    "fluorescent green": "Greens",
    "light bule": "Blues",
    "dark purple": "Purples",
    "leopard print": "Yellows",
    "multicolour": "Multi",
    "golden": "Golds",
    "light purple": "Purples",
    "brown": "Browns",
    "camouflage": "Greens",
    "dark grey": "Grey",
    "navy blue": "Blues",
    "army green": "Greens",
    "coffee": "Brown",
    "dark green": "Greens",
    "dark gray": "Greys",
    "wine red": "Red",
    "camel": "Yellows",
    "ginger": "Beige",
    "vermilion": "Red",
    "fuchsia": "Purples",
    "champagne": "Beige",
    "cow print": "Black",
    "zebra": "Black",
    "leopard": "Yellows",
    "cow pattern": "Black",
    "earthy yellow": "Yellows",
    "saffron": "Saffron",
    "deep red": "Red",
    "fluorescence yellow": "Yellows",
    "light pink": "Pink",
    "purple pink": "Purple pink"
}

us_Size_Mapping = {
    "L": "Large",
    "XXL": "XX-Large",
    "2XL": "XX-Large",
    "L2": "XX-Large",
    "XXXL": "3X-Large",
    "3XL": "3X-Large",
    "L3": "3X-Large",
    "XXXXL": "4X-Large",
    "4XL": "4X-Large",
    "L4": "4X-Large",
    "XXXXXL": "5X-Large",
    "5XL": "5X-Large",
    "XXXXXL": "5X-Large",
    "L5": "5X-Large",
    "XXXXXXL": "6X-Large",
    "6XL": "6X-Large",
    "L6": "6X-Large",
    "XXXXXXXL": "7X-Large",
    "7XL": "7X-Large",
    "L7": "7X-Large",
    "XXXXXXXXL": "8X-Large",
    "8XL": "8X-Large",
    "L8": "8X-Large",
    "M": "Medium",
    "S": "Small",
    "XL": "X-Large",
    "XS": "X-Small",
    "XXS": "XX-Small",
    "2XS": "XX-Small",
    "110": "3 Years", 
    "120": "5 Years", 
    "130": "7 Years", 
    "140": "9 Years", 
    "150": "11 Years", 
    "160": "13 Years", 
}

us_size_map_Mapping = {
    'XXS': 'XXS',
    '2XS': 'XXS',
    'XS': 'XS',
    'S': 'S',
    'M': 'M',
    'L': 'L',
    'XL': 'XL',
    'XXL': 'XXL',
    '2XL': 'XXL',
    'L2': 'XXL',
    'XXXL': '3XL',
    '3XL': '3XL',
    'L3': '3XL',
    'XXXXL': '4XL',
    '4XL': '4XL',
    'L4': '4XL',
    'XXXXXL': '5XL',
    '5XL': '5XL',
    'L5': '5XL',
    'XXXXXXL': '6XL',
    '6XL': '6XL',
    'L6': '6XL',
    'XXXXXXXL': '7XL',
    '7XL': '7XL',
    'L7': '7XL', 
    "110": "3-4 Years", 
    "120": "4-5 Years", 
    "130": "6-7 Years", 
    "140": "8-9 Years", 
    "150": "10-11 Years", 
    "160": "12-13 Years", 

}

Product_Type_Map_New = {
    "衬衫": "shirt",
    "长款上衣": "tunic",
    "运动衫": "sweatshirt",
    "背心": "vest",
    "连衣裙": "dress",
    "半身裙": "skirt",
    "外套": "coat",
    "罩衫": "kimono",
    "夹克": "blazer",
    "裤子": "pants",
    "短裤": "shorts",
    "毛衣": "sweater",
    "领带": "necktie",
    "内裤": "underpants",
    "泳装": "swimwear",
    "袜子": "socks",
    "内衣": "underwear",
    "睡衣": "pajamas",
    "睡袍": "nightgownnightshirt",
    "睡衣": "sleepwear",
    "套装": "suit",
    "长袍": "robe",
    "胸罩": "bra",
    "帽子": "hat",
    "围巾": "scarf",
    "背包": "backpack",
    "手提袋": "totebag",
    "腰带": "apparelbelt",
    "手套": "apparelgloves",
    "配饰": "accessory",
    "民族服装": "ethnicwear"
}

Product_Type_Map = {
    "衬衫": "shirt",
    "长款上衣": "shirt",
    "紧身短袖小衫": "shirt",
    "运动衫": "sweatshirt",
    "背心": "shirt",
    "毛衣": "sweater",
    "外衣": "outerwear",
    "外套": "coat",
    "西装外套": "blazer",
    "短裤": "pants",
    "裤子": "pants",
    "连衣裙": "dress",
    "半身裙": "skirt",
    "紧身胸衣": "shirt",
    "胸罩": "shirt",
    "内衣": "shirt",
    "内裤": "pants",
    "内衣裤": "undergarmentslip",
    "背带": "suspender",
    "手臂套": "armsleeve",
    "游泳衣": "swimwear",
    "运动服": "sweatshirt",
    "工作服": "pants",
    "长袍": "robe",
    "睡袍": "nightgownnightshirt",
    "睡衣两件套": "pajamas",
    "睡衣": "sleepwear",
    "束腰服": "waistcincher",
    "套装": "suit",
    "紧身裤": "tights",
    "紧身连衣裤": "leotard",
    "围裙": "apron",
    "袜子": "socks",
    "针织袜": "sockshosiery",
    "围巾": "scarf",
    "纱丽": "saree",
    "帽子": "hat",
    "背包": "backpack",
    "手提袋": "totebag",
    "护目镜": "safetyglasses",
    "领带": "necktie",
    "腰带": "apparelbelt",
    "行李箱": "luggage",
    "钥匙扣": "keychain",
    "鞋带": "shoelace",
    "耳罩": "earmuff",
    "手套": "apparelgloves",
    "手套": "apparelgloves",
    "防护手套": "protectiveglove",
    "食物围兜": "foodbib",
    "配饰": "accessory"
}

department_name_Map = {
    "女士": "womens",
    "男士": "mens",
    "男女通用": "unisex-adult",
    "女孩": "girls",
    "男孩": "boys",
    "男女孩通用": "Unisex Kids",
    "女婴": "baby-girls",
    "男婴": "baby-boys",
    "男女婴通用": "unisex-baby"
}

site_Map={
    "美国":"US", "德国":"DE", "法国":"FR", "英国":"UK", "加拿大":"CA"
}

age_group_map = {
    "成人": "Adult",
    "大孩子": "TEEN",
    "孩子": "Child",
    "小孩": "Kid",
    "学步的儿童": "Toddler",
    "婴儿": "Baby",
    "新生": "Newborn"
}

gender_map = {
    "女士": "Female",
    "男士": "Male",
    "男女通用": "Unisex",
}

neck_style_map = {
    "圆领": "Crewneck",
    "V领": "V-Neck",
    "船领": "Boat Neck",
    "连帽": "Hooded",
    "露肩": "Off The Shoulder",
    "单肩领": "One Shoulder Neck",
    "高领": "High Neck",
    "无肩带/抹胸": "Strapless/Tube",
    "挂脖露背（Halter）": "Halter",
    "T形背": "Racer Back",
    "U型领": "U-Neck",
    "斜领": "Slash Neck",
    "不对称领口": "Asymmetric Neck",
    "含孔领": "Keyhole Neck",
    "Polo领": "Polo Neck",
    "Henley领": "Henley Neck",
    "纽扣": "Button Front",
    "网孔领": "Eyelet",
    "半拉链": "Half Zip",
    "方领": "Square Neck",
    "风帽领": "Cowl Neck",
    "半高圆领": "Mock Neck",
    "心形颈": "Sweetheart Neck",
    "开叉领": "Split Neck",
    "披肩领": "Shawl Neck",
    "无颈圈领": "Collarless Neck"
}

pattern_map = {
    "纯色": "Solid",
    "简朴": "Plain",
    "条纹": "Stripes",
    "有图案": "Print",
    "文字": "Letter Print",
    "带花图案": "Floral",
    "动物图案": "Animal Print",
    "格子": "Plaid",
    "扎染": "Tie Dye",
    "豹纹": "Leopard",
    "迷彩": "Camouflage",
    "佩斯利纹": "Paisley",
    "波尔卡圆点": "Polka Dots",
    "几何": "Geometric",
    "星星图案": "Stars",
    "水波纹": "Moire",
    "鱼骨纹": "Herringbone",
    "锯齿纹": "Chevron",
    "植物图案": "Botanical",
    "菱形格": "Argyle",
    "水果": "Fruit",
    "拼色": "Color Block",
    "银河": "Galaxy",
    "圣诞节": "Christmas",
    "卡通": "Cartoon",
    "犬牙花纹": "Houndstooth",
    "水果和蔬菜": "Fruit and Vegetable",
    "爱心": "Hearts",
    "蛇皮图案": "Snakeskin Print",
    "钻石": "Diamond",
}


title_map = {
    "纯色": "Solid Color",
    "简朴": "Plain",
    "条纹": "Stripes",
    "有图案": "Print",
    "文字": "Letter Print",
    "带花图案": "Floral Print",
    "动物图案": "Animal Print",
    "格子": "Plaid",
    "扎染": "Tie Dye",
    "豹纹": "Leopard",
    "迷彩": "Camouflage",
    "佩斯利纹": "Paisley",
    "波尔卡圆点": "Polka Dots",
    "几何": "Geometric Print",
    "阿兹特克画像": "Aztec Print",
    "星星图案": "Stars Print",
    "水波纹": "Moire",
    "人字纹": "Herringbone",
    "人字形": "Chevron",
    "植物图案": "Botanical",
    "菱形格": "Argyle",
    "水果": "Fruit",
    "拼色": "Color Block",
    "银河": "Galaxy",
    "圣诞节": "Christmas",
    "卡通": "Cartoon",
    "犬牙花纹": "Houndstooth",
    "水果和蔬菜": "Fruit and Vegetable",
    "爱心": "Hearts",
}

clothing_style_map = {
    "经典": "Classic",
    "复古": "Retro",
    "现代": "Modern",
    "传统": "Traditional",
    "波西米亚风": "Bohemian",
    "休闲": "Casual",
    "优质": "Vintage",
}

skirt_length_map = {
    "超长": "Floor Length",
    "长裙": "Maxi",
    "到脚踝": "Ankle Length",
    "到小腿": "Calf Length",
    "中长裙": "Midi",
    "膝盖以下": "Below the Knee",
    "到膝盖": "Knee Length",
    "膝盖以上": "Above the Knee",
    "到大腿中部": "Mid Thigh Length",
    "短裙": "Mini"
}

fit_map = {
    "宽松": "Loose",
    "合身": "Fitted",
    "苗条": "Slim",
    "紧身": "Skinny Fit"
}

closure_map = {
    "穿上": "Pull-On",
    "拉链": "Zipper",
    "按钮": "Button",
    "无关闭": "No Closure",
    "绑上": "Tie",
    "系腰带": "Belted",
    "扣上": "Buckle",
    "拉绳": "Drawstring",
    "钩": "Hook"
}

pocket_map = {
    "立体口袋": "Cargo",
    "工具口袋": "Carpenter",
    "无后袋": "No Back Pocket",
    "斜口袋": "Slant Pocket",
    "狭缝口袋": "Slit Pocket",
    "多用途口袋": "Utility Pocket",
    "直插口袋": "Straight Pocket",
    "开缝口袋": "Welt Pocket",
    "翻盖口袋": "Flap Pocket",
    "零钱袋": "Coin Pocket",
    "票袋": "Ticket Pocket",
    "斜线口袋": "Slash Pocket"
}

sleeve_map = {
    "长袖": "Long Sleeve",
    "短袖": "Short Sleeve",
    "无袖": "Sleeveless",
    "3/4 袖": "3/4 Sleeve",
    "半袖": "Half Sleeve",
    "背心": "Tanks",
    "露肩袖": "Cold Shoulder Sleeve",
    "和服袖": "Kimono Sleeve",
    "荷叶袖": "Ruffle Sleeve",
    "泡泡袖": "Puff Sleeve",
    "喇叭袖": "Bell Sleeve",
    "蝙蝠袖": "Batwing Sleeve",
    "蝴蝶袖": "Butterfly Sleeve",
    "气球袖": "Balloon Sleeve",
    "斗篷袖": "Cape Sleeve"
}

top_style_map = {
    "按钮": "Button Down",
    "吊带": "Cami",
    "挂脖": "Halter",
    "单肩": "One Shoulder",
    "T形背": "Racerback",
    "无肩带/管": "Strapless/Tube",
    "文胸": "Bralette",
    "露肩": "Off The Shoulder",
    "高领": "High Neck",
    "喇叭形": "Flared",
    "交叉背": "Crossback",
    "防晒衣": "Rashguard",
    "背心比基尼": "Tankini",
    "无上装比基尼": "Monokini",
    "延绳钓": "Longline",
    "抹胸": "Bandeau",
    "Push Up": "Push Up"
}

seasons_map = {
    "春天": "Spring",
    "夏天": "Summer",
    "秋天": "Autumn",
    "冬天": "Winter",
    "四季": "All"
}

#----------------------------------------

leg_style_map = {
    "脚踝": "Ankle",
    "靴型剪裁": "Boot Cut",
    "裁剪": "Cropped",
    "喇叭裤": "Flared",
    "紧身": "Skinny",
    "直筒": "Straight",
    "锥形": "Tapered",
    "裤装": "Trouser",
    "宽松": "Wide"
}

waist_style_map ={
"中腰": "Medium Waist",
"高腰": "High Waist",
"低腰": "Low Waist"
}

# item_type_map={
#     "衬衫": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"], 

#     "长款上衣": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"], 
    
#     "紧身短袖小衫": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"],
    
#     "运动衫": ["Sweater", "Hooded Sweatshirt", "Sweatshirt", "Cardigan Sweater", 
#     "Pullover Sweater", "Polo Sweater", "Sweater Vest", "Sweater", 
#     "Hooded Sweatshirt", "Sweatshirt", "Cardigan Sweater", "Pullover Sweater", 
#     "Polo Sweater", "Sweater Vest", "Sweater"],

#     "西装外套":["Business Casual Blazer", "Casual Blazer", "Sport Jacket", "Blazer"],

#     "胸罩": ["T-Shirt Bra", "Training Bra", "Full Coverage Bra", "Plunge Bra", 
#              "Sports Bra", "Bra", "Padded Bra", "Demi Bra", "Minimizer Bra", 
#              "Balconette Bra", "Push Up Bra"],

#     "游泳衣": ["One Piece Swimsuit", "Swim Trunks", "Tankini Set", "Swimwear Cover Up", 
#                   "Swimsuit Separates", "Swim Briefs", "Bikini Top", "Swim Shirt Set", 
#                   "Swimwear Cover Up Set", "Tankini Top", "Tankini Swimsuit", "Bikini Bottoms", 
#                   "Bikini", "Bikini Set", "Two Piece Swimsuit"],

#     "睡衣两件套/睡袍": ["Pajama Top", "Nightgown", "Bathrobe", "Pajama Bottom", "Night Shirt", 
#                    "Pajama Set"],

#     "套装": ["Business Suit Jacket", "Tuxedo Pants", "Tuxedo", "Tuxedo Jacket", 
#               "Suit - Skirt Set", "Suit - Dress Set", "Business Suit Vest", 
#               "Business Suit Pants Set"],

#     "帽子": ["Rain Hat", "Cowboy Hat", "Baseball Cap", "Sun Hat", "Cap", 
#              "Cold Weather Hat", "Hat", "Beanie Hat", "Cold Weather Headband"],
    
# }