column_headers = [
    "feed_product_type", "item_sku", "brand_name", "update_delete", "item_name", 
    "color_name", "color_map", "size_name", "size_map", "generic_keywords", 
    "bullet_point1", "bullet_point2", "bullet_point3", "bullet_point4", "bullet_point5", 
    "product_description", "standard_price", "sale_price", "sale_from_date", "sale_end_date", 
    "product_site_launch_date", "merchant_release_date", "recommended_browse_nodes", 
    "external_product_id", "external_product_id_type", "main_image_url", "other_image_url1", 
    "other_image_url2", "other_image_url3", "other_image_url4", "other_image_url5", "other_image_url6", "other_image_url7", "other_image_url8",
    "swatch_image_url", "parent_child", "parent_sku", "relationship_type", "variation_theme", 
    "material_composition", "care_instructions", "closure_type", "neck_style", "weave_type", 
    "department_name", "sleeve_type", "merchant_shipping_group_name", "model", "part_number", 
    "model_name", "outer_material_type", "manufacturer", "language_value1", "quantity", 
    "inner_material_type", "target_gender", "age_range_description", "apparel_size_system", 
    "apparel_size_class", "apparel_size", "apparel_body_type", "apparel_height_type", 
    "shapewear_size_system", "shapewear_size_class", "shapewear_size", "shapewear_body_type", 
    "shapewear_height_type", "bottoms_size_system", "bottoms_size_class", "bottoms_size", 
    "bottoms_body_type", "bottoms_height_type", "skirt_size_system", "skirt_size_class", 
    "skirt_size", "skirt_body_type", "skirt_height_type", "shirt_size_system", "shirt_size_class", 
    "shirt_size", "shirt_body_type", "shirt_height_type", "style_name", "is_autographed", 
    "item_type_name", "occasion_type1", "occasion_type2", "occasion_type3", "occasion_type4", 
    "occasion_type5", "sport_type1", "sport_type2", "collection_name", "material_type1", 
    "material_type2", "material_type3", "target_audience_keywords1", "target_audience_keywords2", 
    "target_audience_keywords3", "target_audience_keywords4", "target_audience_keywords5", 
    "lifestyle1", "lifestyle2", "lifestyle3", "lifestyle4", "lifestyle5", "lifestyle6", 
    "lifestyle7", "lifestyle8", "lifestyle9", "lifestyle10", "fur_description", "fit_type1", 
    "fit_type2", "fit_type3", "fit_type4", "fit_type5", "collar_style", "pocket_description", 
    "theme", "lining_description", "league_name", "lifecycle_supply_type", "pattern_name", 
    "pattern_type", "special_features1", "special_features2", "special_features3", 
    "special_features4", "special_features5", "special_features6", "special_features7", 
    "platinum_keywords1", "platinum_keywords2", "platinum_keywords3", "platinum_keywords4", 
    "platinum_keywords5", "seasons", "number_of_boxes", "water_resistance_level", "number_of_pieces", 
    "top_style", "rise_style", "front_style", "fabric_wash", "bottom_style", "strap_type", 
    "number_of_pockets", "waist_style", "item_length_description", "band_size_num", 
    "band_size_num_unit_of_measure", "country_of_origin", "supplier_declared_dg_hz_regulation1", 
    "item_weight", "item_weight_unit_of_measure", "fabric_type", "flash_point", 
    "supplier_declared_material_regulation1", "cpsia_cautionary_statement1", "condition_type", 
    "currency", "number_of_items", "map_price", "list_price_with_tax", "item_package_quantity", 
    "list_price", "other_image_url_ps06"
]

column_map = {
            "SKU": None,
            "颜色": None,
            "尺寸": None,
            "水洗唛材质": None,
            "亚马逊建议价": None,
            "代理链接 1": None,
            "代理链接 2": None,
            "代理链接 3": None,
            "代理链接 4": None,
            "代理链接 5": None,
            "代理链接 6": None,
            "代理链接 7": None,
            "代理链接 8": None,
            "代理链接 9": None
        }

# 创建颜色哈希表
de_color_Map = {
    "brown": "Braun",
    "purple pink": "Lila pink",
    "purple": "Lila",
    "vermilion": "Zinnober",
    "fluorescent green": "Leuchtendes Grün",
    "fluorescence yellow": "Fluoreszenzgelb",
    "fuchsia": "Fuchsie",
    "silver": "Silber",
    "champagne": "Sekt",
    "watermelon red": "Wassermelonenrot",
    "camouflage": "Tarnung",
    "sky blue": "Himmelblau",
    "dark purple": "Dunkelviolett",
    "dark green": "Dunkelgrün",
    "dark blue": "Dunkelblau",
    "deep blue": "Tiefes Blau",
    "dark gray": "Dunkelgrau",
    "dark grey": "Dunkelgrau",
    "deep red": "Tiefrot",
    "dark red": "Dunkelrot",
    "snake pattern": "Schlangenmuster",
    "colorful": "Bunt",
    "clear": "Transparent",
    "bronze": "Bronze",
    "cyan": "Cyan",
    "light brown": "Hellbraun",
    "light purple": "Helles Lila",
    "light blue": "Hellblau",
    "light gray": "Hellgrau",
    "earthy yellow": "Erdig gelb",
    "cow pattern": "Kuh-Muster",
    "cow print": "Kuh-Druck",
    "beige": "Beige",
    "rose gold": "Roségold",
    "turquoise": "Türkis",
    "green": "Grün",
    "camel": "Kamel",
    "light green": "Hellgrün",
    "light pink": "Hell-Pink",
    "light bule": "Hellblau",
    "blue": "Blau",
    "khaki": "Khaki",
    "coffee": "Kaffee",
    "army green": "Armeegrün",
    "wine red": "Weinrot",
    "wine": "Weinrot",
    "golden": "Golden",
    "ginger": "Ingwer",
    "gray": "Grau",
    "grey": "Grau",
    "yellow": "Gelb",
    "gold": "Gold",
    "royal blue": "Königsblau",
    "red": "Rot",
    "black": "Schwarz",
    "navy blue": "Marine",
    "navy": "Marine",
    "complexion": "Teint",
    "pink": "Rosa",
    "hot pink": "Pink",
    "multicolor": "Mehrfarbig",
    "multicolour": "Mehrfarben",
    "orange": "Orange",
    "saffron": "Safrangelb",
    "ecru": "Ecru",
    "leopard print": "Leopardenmuster",
    "leopard": "Leopard",
    "mint green": "Minzgrün",
    "zebra": "Zebra",
    "white": "Weiß",
    "multcolor": "Mehrfarbig"
}

de_color_map_Map = {
    "brown": "Braun",
    "purple pink": "Lila",
    "purple": "Lila",
    "vermilion": "Rot",
    "fluorescent green": "Türkis",
    "fluorescence yellow": "Gelb",
    "fuchsia": "Rot",
    "silver": "Silber",
    "champagne": "Gelb",
    "watermelon red": "Rot",
    "camouflage": "Multi",
    "sky blue": "Türkis",
    "dark purple": "Lila",
    "dark green": "Grün",
    "dark blue": "Blau",
    "deep blue": "Blau",
    "dark gray": "Grau",
    "dark grey": "Grau",
    "deep red": "Rot",
    "dark red": "Rot",
    "snake pattern": "Multi",
    "colorful": "Multi",
    "clear": "Transparent",
    "bronze": "Braun",
    "cyan": "Grün",
    "light brown": "Braun",
    "light purple": "Lila",
    "light blue": "Türkis",
    "light gray": "Elfenbein",
    "earthy yellow": "Beige",
    "cow pattern": "Multi",
    "cow print": "Multi",
    "beige": "Beige",
    "rose gold": "Rosa",
    "turquoise": "Türkis",
    "green": "Grün",
    "camel": "Braun",
    "light green": "Türkis",
    "light pink": "Rosa",
    "light bule": "Türkis",
    "blue": "Blau",
    "khaki": "Beige",
    "coffee": "Braun",
    "army green": "Multi",
    "wine red": "Rot",
    "wine": "Rot",
    "golden": "Gold",
    "ginger": "Beige",
    "gray": "Grau",
    "grey": "Grau",
    "yellow": "Gelb",
    "gold": "Gold",
    "royal blue": "Türkis",
    "red": "Rot",
    "black": "Schwarz",
    "navy blue": "Blau",
    "navy": "Blau",
    "complexion": "Elfenbein",
    "pink": "Rosa",
    "hot pink": "Rosa",
    "multicolor": "Multi",
    "multicolour": "Multi",
    "orange": "Orange",
    "saffron": "Rot",
    "ecru": "Beige",
    "leopard print": "Multi",
    "leopard": "Multi",
    "mint green": "Grün",
    "zebra": "Multi",
    "white": "Weiß",
    "multcolor": "Multi"
}


us_Size_Mapping = {
    "XXS": "XXS",
    "2XS": "XXS",
    "XS": "XS",
    "S": "S",
    "M": "M",
    "L": "L",
    "XL": "XL",
    "XXL": "XXL",
    "2XL": "XXL",
    "L2": "XXL",
    "XXXL": "3XL",
    "3XL": "3XL",
    "L3": "3XL",
    "XXXXL": "4XL",
    "4XL": "4XL",
    "L4": "4XL",
    "XXXXXL": "5XL",
    "5XL": "5XL",
    "L5": "5XL",
    "XXXXXXL": "6XL",
    "6XL": "6XL",
    "L6": "6XL",
    "XXXXXXXL": "7XL",
    "7XL": "7XL",
    "L7": "7XL", 
    "110": "3 Jahre", 
    "120": "5 Jahre", 
    "130": "7 Jahre", 
    "140": "9 Jahre", 
    "150": "11 Jahre", 
    "160": "13 Jahre", 
    "One Size": "Einheitsgröße", 
}

us_size_map_Mapping = {
    'XXS': '2XS',
    '2XS': '2XS',
    'XS': 'XS',
    'S': 'S',
    'M': 'M',
    'L': 'L',
    'XL': 'XL',
    'XXL': '2XL',
    '2XL': '2XL',
    'L2': '2XL',
    'XXXL': '3XL',
    '3XL': '3XL',
    'L3': '3XL',
    'XXXXL': '4XL',
    '4XL': '4XL',
    'L4': '4XL',
    'XXXXXL': '5XL',
    '5XL': '5XL',
    'L5': '5XL',
    'XXXXXXL': '6XL',
    '6XL': '6XL',
    'L6': '6XL',
    'XXXXXXXL': '7XL',
    '7XL': '7XL',
    'L7': '7XL', 
    "110": "3-4 Jahre(110)", 
    "120": "4-5 Jahre(120)", 
    "130": "6-7 Jahre(130)", 
    "140": "8-9 Jahre(140)", 
    "150": "10-11 Jahre(150)", 
    "160": "12-13 Jahre(160)", 
    "One Size": "Einheitsgröße", 
}

Product_Type_Map_New = {
    "衬衫": "shirt",
    "长款上衣": "tunic",
    "运动衫": "sweatshirt",
    "背心": "vest",
    "连衣裙": "dress",
    "半身裙": "skirt",
    "外套": "coat",
    "罩衫": "kimono",
    "夹克": "blazer",
    "裤子": "pants",
    "短裤": "shorts",
    "毛衣": "sweater",
    "领带": "necktie",
    "内裤": "underpants",
    "泳装": "swimwear",
    "袜子": "socks",
    "内衣": "underwear",
    "睡衣": "pajamas",
    "睡袍": "nightgownnightshirt",
    "睡衣": "sleepwear",
    "套装": "suit",
    "长袍": "robe",
    "胸罩": "bra",
    "帽子": "hat",
    "围巾": "scarf",
    "背包": "backpack",
    "手提袋": "totebag",
    "腰带": "apparelbelt",
    "手套": "apparelgloves",
    "配饰": "accessory",
    "民族服装": "ethnicwear"
}

Product_Type_Map = {
    "衬衫": "shirt",
    "长款上衣": "shirt",
    "紧身短袖小衫": "shirt",
    "运动衫": "sweatshirt",
    "背心": "shirt",
    "毛衣": "sweater",
    "外衣": "outerwear",
    "外套": "coat",
    "西装外套": "blazer",
    "短裤": "pants",
    "裤子": "pants",
    "连衣裙": "dress",
    "半身裙": "skirt",
    "紧身胸衣": "shirt",
    "胸罩": "shirt",
    "内衣": "shirt",
    "内裤": "pants",
    "内衣裤": "undergarmentslip",
    "背带": "suspender",
    "手臂套": "armsleeve",
    "游泳衣": "swimwear",
    "运动服": "sweatshirt",
    "工作服": "pants",
    "长袍": "robe",
    "睡袍": "nightgownnightshirt",
    "睡衣两件套": "pajamas",
    "睡衣": "sleepwear",
    "束腰服": "waistcincher",
    "套装": "suit",
    "紧身裤": "tights",
    "紧身连衣裤": "leotard",
    "围裙": "apron",
    "袜子": "socks",
    "针织袜": "sockshosiery",
    "围巾": "scarf",
    "纱丽": "saree",
    "帽子": "hat",
    "背包": "backpack",
    "手提袋": "totebag",
    "护目镜": "safetyglasses",
    "领带": "necktie",
    "腰带": "apparelbelt",
    "行李箱": "luggage",
    "钥匙扣": "keychain",
    "鞋带": "shoelace",
    "耳罩": "earmuff",
    "手套": "apparelgloves",
    "手套": "apparelgloves",
    "防护手套": "protectiveglove",
    "食物围兜": "foodbib",
    "配饰": "accessory"
}

department_name_Map = {
    "女士": "Damen",
    "男士": "Herren",
    "男女通用": "Unisex",
    "女孩": "Mädchen",
    "男孩": "Jungen",
    "男女孩通用": "Unisex Kinder",
    "女婴": "Baby - Mädchen",
    "男婴": "Baby - Jungen",
    "男女婴通用": "Unisex Baby"
}

site_Map={
    "美国":"US", "德国":"DE", "法国":"FR", "英国":"UK", "加拿大":"CA"
}

age_group_map = {
    "成人": "Erwachsener",
    "大孩子": "TEEN",
    "孩子": "Kind",
    "小孩": "Kleinkind",
    "学步的儿童": "Baby",
    "婴儿": "Säugling",
    "新生": "Neugeboren"
}

gender_map = {
    "女士": "Weiblich",
    "男士": "Männlich",
    "男女通用": "Unisex",
}

neck_style_map = {
    "圆领": "Rundhals-Ausschnitt",
    "V领": "V-Ausschnitt",
    "船领": "U-Boot-Ausschnitt",
    "连帽": "Kapuze",
    "露肩": "Off The Shoulder",
    "单肩领": "One-Shoulder-Ausschnitt",
    "高领": "Rollkragen",
    "无肩带/抹胸": "Bandeau",
    "挂脖露背（Halter）": "Halter_neck",
    "T形背": "Racerback",
    "U型领": "U_neck",
    "斜领": "Slash Neck",
    "不对称领口": "Asymmetrischer Hals",
    "含孔领": "Keyhole-Ausschnitt",
    "Polo领": "Polo-Ausschnitt",
    "Henley领": "Henley Ausschnitt",
    "纽扣": "Knopfleiste",
    "网孔领": "Eyelet",
    "半拉链": "Halber Reißverschluss",
    "方领": "Karree Ausschnitt",
    "半高圆领": "Mock Ausschnitt",
    "心形颈": "Herzausschnitt",
    "开叉领": "Split-Ausschnitt",
    "披肩领": "Schalkragen",
    "无领领口": "Ohne Kragen"
}

pattern_map = {
    "纯色": "Einfarbig",
    "简朴": "Uni",
    "条纹": "Gestreift",
    "有图案": "Druck",
    "文字": "Buchstabenmuster",
    "带花图案": "Geblümt",
    "动物图案": "Tier-Druck",
    "格子": "Kariert",
    "扎染": "Tie Dye",
    "豹纹": "Leopard",
    "迷彩": "Camouflage",
    "佩斯利纹": "Paisley",
    "波尔卡圆点": "Gepunktet",
    "几何": "Geometrisch",
    "星星图案": "Sterne",
    "水波纹": "Moiré",
    "鱼骨纹": "Fischgrätmuster",
    "锯齿纹": "Chevron",
    "植物图案": "Pflanzen",
    "菱形格": "Argyle",
    "水果": "Früchte",
    "拼色": "Farbblock",
    "银河": "Galaxie",
    "圣诞节": "Weihnacht",
    "卡通": "Cartoon",
    "犬牙花纹": "Hahnentritt",
    "水果和蔬菜": "Obst & Gemüse",
    "爱心": "Herzen",
    "钻石": "Diamant",
    "蛇皮图案": "Schlangenhaut-Print",
}

clothing_style_map = {
    "经典": "Classic",
    "复古": "Retro",
    "现代": "Modern",
    "传统": "Traditional",
    "波西米亚风": "Bohemian",
    "休闲": "Casual",
    "优质": "Vintage",
}

skirt_length_map = {
    "超长": "Floor Length",
    "长裙": "Maxi",
    "到脚踝": "Ankle Length",
    "到小腿": "Calf Length",
    "中长裙": "Midi",
    "膝盖以下": "Below the Knee",
    "到膝盖": "Knee Length",
    "膝盖以上": "Above the Knee",
    "到大腿中部": "Mid Thigh Length",
    "短裙": "Mini"
}

fit_map = {
    "宽松": "Loose",
    "合身": "Fitted",
    "苗条": "Slim",
    "紧身": "Skinny Fit"
}

closure_map = {
    "系腰带": "Bindegürtel",
    "扣上": "Schnalle",
    "拉链": "Reißverschluss",
    "绑上": "Krawatte",
    "按钮": "Druckknopf",
    "拉绳": "Tunnelzug",
    "穿上": "Pull-on",
    "无关闭": "no_closure",
    "钩": "Haken"
}

pocket_map = {
    "立体口袋": "Cargo",
    "工具口袋": "Carpenter",
    "无后袋": "No Back Pocket",
    "斜口袋": "Slant Pocket",
    "狭缝口袋": "Slit Pocket",
    "多用途口袋": "Utility Pocket",
    "直插口袋": "Straight Pocket",
    "开缝口袋": "Welt Pocket",
    "翻盖口袋": "Flap Pocket",
    "零钱袋": "Coin Pocket",
    "票袋": "Ticket Pocket",
    "斜线口袋": "Slash Pocket"
}

sleeve_map = {
    "长袖": "Long Sleeve",
    "短袖": "Short Sleeve",
    "无袖": "Sleeveless",
    "3/4 袖": "3/4 Sleeve",
    "半袖": "Half Sleeve",
    "背心": "Tanks",
    "露肩袖": "Cold Shoulder Sleeve",
    "和服袖": "Kimono Sleeve",
    "荷叶袖": "Ruffle Sleeve",
    "泡泡袖": "Puff Sleeve",
    "喇叭袖": "Bell Sleeve",
    "蝙蝠袖": "Batwing Sleeve",
    "蝴蝶袖": "Butterfly Sleeve",
    "气球袖": "Balloon Sleeve",
    "斗篷袖": "Cape Sleeve"
}

top_style_map = {
    "按钮": "Button Down",
    "吊带": "Cami",
    "挂脖": "Halter",
    "单肩": "One Shoulder",
    "T形背": "Racerback",
    "无肩带/管": "Strapless/Tube",
    "文胸": "Bralette",
    "露肩": "Off The Shoulder",
    "高领": "High Neck",
    "喇叭形": "Flared",
    "交叉背": "Crossback",
    "防晒衣": "Rashguard",
    "背心比基尼": "Tankini",
    "无上装比基尼": "Monokini",
    "延绳钓": "Longline",
    "抹胸": "Bandeau",
    "Push Up": "Push Up"
}

seasons_map = {
    "春天": "Spring",
    "夏天": "Summer",
    "秋天": "Autumn",
    "冬天": "Winter",
    "四季": "All"
}

#----------------------------------------

leg_style_map = {
    "脚踝": "Ankle",
    "靴型剪裁": "Boot Cut",
    "裁剪": "Cropped",
    "喇叭裤": "Flared",
    "紧身": "Skinny",
    "直筒": "Straight",
    "锥形": "Tapered",
    "裤装": "Trouser",
    "宽松": "Wide"
}

waist_style_map ={
"中腰": "Medium Waist",
"高腰": "High Waist",
"低腰": "Low Waist"
}

# item_type_map={
#     "衬衫": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"], 

#     "长款上衣": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"], 
    
#     "紧身短袖小衫": ["Cami Shirt", "T-Shirt", "Button Down Shirt", "Skate Shirt", "Tennis Shirt",
#     "Shirt", "Polo Shirt", "Vest", "Henley Shirt", "Yoga Shirt",
#     "Hiking Shirt", "Blouse", "Dress Shirt", "Fashion Vest", "Tunic Shirt"],
    
#     "运动衫": ["Sweater", "Hooded Sweatshirt", "Sweatshirt", "Cardigan Sweater", 
#     "Pullover Sweater", "Polo Sweater", "Sweater Vest", "Sweater", 
#     "Hooded Sweatshirt", "Sweatshirt", "Cardigan Sweater", "Pullover Sweater", 
#     "Polo Sweater", "Sweater Vest", "Sweater"],

#     "西装外套":["Business Casual Blazer", "Casual Blazer", "Sport Jacket", "Blazer"],

#     "胸罩": ["T-Shirt Bra", "Training Bra", "Full Coverage Bra", "Plunge Bra", 
#              "Sports Bra", "Bra", "Padded Bra", "Demi Bra", "Minimizer Bra", 
#              "Balconette Bra", "Push Up Bra"],

#     "游泳衣": ["One Piece Swimsuit", "Swim Trunks", "Tankini Set", "Swimwear Cover Up", 
#                   "Swimsuit Separates", "Swim Briefs", "Bikini Top", "Swim Shirt Set", 
#                   "Swimwear Cover Up Set", "Tankini Top", "Tankini Swimsuit", "Bikini Bottoms", 
#                   "Bikini", "Bikini Set", "Two Piece Swimsuit"],

#     "睡衣两件套/睡袍": ["Pajama Top", "Nightgown", "Bathrobe", "Pajama Bottom", "Night Shirt", 
#                    "Pajama Set"],

#     "套装": ["Business Suit Jacket", "Tuxedo Pants", "Tuxedo", "Tuxedo Jacket", 
#               "Suit - Skirt Set", "Suit - Dress Set", "Business Suit Vest", 
#               "Business Suit Pants Set"],

#     "帽子": ["Rain Hat", "Cowboy Hat", "Baseball Cap", "Sun Hat", "Cap", 
#              "Cold Weather Hat", "Hat", "Beanie Hat", "Cold Weather Headband"],
    
# }